name: task_manager
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  android_alarm_manager_plus: ^3.0.4
  cloud_firestore: ^4.13.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^16.2.0
  flutter_login: ^4.2.1
  flutter_ringtone_player: ^4.0.0+2
  flutter_system_ringtones: ^0.0.6
  intl: ^0.18.1
  sensors_plus: ^4.0.2
  shared_preferences: ^2.2.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
